package com.whx.router.helper.module_user.service;

import androidx.annotation.Nullable;

import com.whx.module_common.route.service.user.PayService;
import com.whx.module_common.route.service.user.PayService;
import com.whx.router.MRouter;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MROUTER.
 * 微信Pay服务
 * {@link com.whx.module_user.route.service.WechatPayServiceImpl}
 */
public class PayServiceForWechatPayGoRouter {
    @Nullable
    public static PayService get() {
        return MRouter.getInstance().getService(PayService.class, "WechatPay");
    }
}
