package com.whx.router.helper.module_user.service;

import androidx.annotation.Nullable;

import com.whx.module_common.route.service.user.UserService;
import com.whx.module_common.route.service.user.UserService;
import com.whx.router.MRouter;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MROUTER.
 * 用户服务
 * {@link com.whx.module_user.route.service.UserServiceImpl}
 */
public class UserServiceGoRouter {
    @Nullable
    public static UserService get() {
        return MRouter.getInstance().getService(UserService.class);
    }
}
