package com.whx.router.helper.module_kotlin.service;

import androidx.annotation.Nullable;

import com.whx.module_common.route.service.user.UserService;
import com.whx.module_common.route.service.user.UserService;
import com.whx.router.MRouter;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MROUTER.
 * Kotlin模块用户服务
 * {@link com.whx.module_kotlin.route.service.KotlinUserServiceImpl}
 */
public class UserServiceForKotlinGoRouter {
    @Nullable
    public static UserService get() {
        return MRouter.getInstance().getService(UserService.class, "Kotlin");
    }
}
