package com.whx.router.helper.module_user.group_new;

import androidx.annotation.Nullable;

import com.whx.module_common.model.TestModel;
import com.whx.router.MRouter;
import com.whx.router.model.Card;
import com.whx.router.model.CardMeta;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MROUTER.
 * 参数页面
 * {@link com.whx.module_user.activity.ParamActivity}
 */
public class NewParamActivityGoRouter {
    public static String getPath() {
        return "/new/param/activity";
    }

    @Nullable
    public static CardMeta getCardMeta() {
        return MRouter.getInstance().build(getPath()).getCardMeta();
    }

    public static <T> void postEvent(T value) {
        MRouter.getInstance().postEvent(getPath(), value);
    }

    public static Card build(String nickname, TestModel test) {
        return MRouter.getInstance().build(getPath())
                // 昵称
                .withString("nickname", nickname)
                // 自定义类型
                .withObject("test", test);
    }

    public static void go(String nickname, TestModel test) {
        build(nickname, test).go();
    }

    public static Builder create(String nickname, TestModel test) {
        return new Builder(nickname, test);
    }

    public static Card build(String nickname, TestModel test,
            int base, int age) {
        return create(nickname, test).setBase(base).setAge(age).build();
    }

    public static void go(String nickname, TestModel test, int base,
                          int age) {
        build(nickname, test, base, age).go();
    }

    public static class Builder {
        private final Card mCard;

        public Builder(String nickname, TestModel test) {
            mCard = MRouter.getInstance().build(getPath())
                    // 昵称
                    .withString("nickname", nickname)
                    // 自定义类型
                    .withObject("test", test);
        }

        /**
         * 我是一个父类字段
         */
        public Builder setBase(int base) {
            mCard.withInt("base", base);
            return this;
        }

        public Builder setAge(int age) {
            mCard.withInt("age", age);
            return this;
        }

        public Card build() {
            return mCard;
        }
    }
}
