package com.whx.router.helper.module_user.group_new;

import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import com.whx.router.MRouter;
import com.whx.router.model.Card;
import com.whx.router.model.CardMeta;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MROUTER.
 * 参数片段
 * {@link com.whx.module_user.fragment.ParamFragment}
 */
public class NewParamFragmentGoRouter {
    public static String getPath() {
        return "/new/param/fragment";
    }

    @Nullable
    public static CardMeta getCardMeta() {
        return MRouter.getInstance().build(getPath()).getCardMeta();
    }

    public static <T> void postEvent(T value) {
        MRouter.getInstance().postEvent(getPath(), value);
    }

    public static Card build() {
        return MRouter.getInstance().build(getPath());
    }

    @Nullable
    public static Fragment go() {
        return (Fragment) build().go();
    }

    public static Builder create() {
        return new Builder();
    }

    public static Card build(int age, String name) {
        return create().setAge(age).setName(name).build();
    }

    @Nullable
    public static Fragment go(int age, String name) {
        return (Fragment) build(age, name).go();
    }

    public static class Builder {
        private final Card mCard;

        public Builder() {
            mCard = MRouter.getInstance().build(getPath());
        }

        public Builder setAge(int age) {
            mCard.withInt("age", age);
            return this;
        }

        public Builder setName(String name) {
            mCard.withString("name", name);
            return this;
        }

        public Card build() {
            return mCard;
        }
    }
}
