package com.whx.router.helper.module_main.group_main;

import androidx.annotation.Nullable;

import com.whx.router.model.Card;
import com.whx.router.model.CardMeta;
import com.whx.router.MRouter;
import com.whx.router.model.Card;
import com.whx.router.model.CardMeta;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MROUTER.
 * 欢迎页
 * {@link com.whx.module_main.activity.SplashActivity}
 */
public class MainSplashActivityGoRouter {
    public static String getPath() {
        return "/main/splash/activity";
    }

    @Nullable
    public static CardMeta getCardMeta() {
        return MRouter.getInstance().build(getPath()).getCardMeta();
    }

    public static <T> void postEvent(T value) {
        MRouter.getInstance().postEvent(getPath(), value);
    }

    public static Card build() {
        return MRouter.getInstance().build(getPath());
    }

    public static void go() {
        build().go();
    }
}
