package com.whx.router.helper.module_user.group_user;

import androidx.annotation.Nullable;
import com.whx.router.MRouter;
import com.whx.router.model.Card;
import com.whx.router.model.CardMeta;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MROUTER.
 * 登录页面
 * {@link com.whx.module_user.activity.SignInActivity}
 */
public class UserSignInActivityGoRouter {
    public static String getPath() {
        return "/user/sign_in/activity";
    }

    @Nullable
    public static CardMeta getCardMeta() {
        return MRouter.getInstance().build(getPath()).getCardMeta();
    }

    public static <T> void postEvent(T value) {
        MRouter.getInstance().postEvent(getPath(), value);
    }

    public static Card build() {
        return MRouter.getInstance().build(getPath());
    }

    public static void go() {
        build().go();
    }
}
